### ISSUE TITLE
attempt to write a readonly database (8)

### ISSUE THREAD

**Issue by WizardlyBump17** [muety/wakapi#692] opened 2024-10-14 21:37 UTC
Hi. I am following the docker step (not compose and I dont assign a name to the container and I dont detach). Looks like everything works, but when I try to toggle the "Participate in leaderboard" option I get: "Error: Internal sever error". The docker log shows the following:
```
{"time":"2024-10-14T21:27:16.266982403Z","level":"INFO","msg":"👉 Listening for HTTP... ✅","address":"0.0.0.0:3000"}
{"time":"2024-10-14T21:27:23.889748625Z","level":"INFO","msg":"[request]","status":302,"method":"POST","uri":"/settings","duration":719439,"bytes":0,"addr":"172.17.0.1:34510","user":"-"}
{"time":"2024-10-14T21:27:23.8980648Z","level":"INFO","msg":"[request]","status":200,"method":"GET","uri":"/","duration":981700,"bytes":8783,"addr":"172.17.0.1:34510","user":"-"}
{"time":"2024-10-14T21:27:24.889445095Z","level":"INFO","msg":"[request]","status":200,"method":"GET","uri":"/login","duration":1750580,"bytes":3912,"addr":"172.17.0.1:34524","user":"-"}
{"time":"2024-10-14T21:27:28.856822205Z","level":"INFO","msg":"[request]","status":302,"method":"POST","uri":"/login","duration":26626390,"bytes":0,"addr":"172.17.0.1:34544","user":"-"}
{"time":"2024-10-14T21:27:28.927369988Z","level":"INFO","msg":"[request]","status":302,"method":"GET","uri":"/summary?interval=today","duration":63078635,"bytes":33892,"addr":"172.17.0.1:34544","user":"WizardlyBump17"}
{"time":"2024-10-14T21:27:28.961919577Z","level":"INFO","msg":"[request]","status":200,"method":"GET","uri":"/summary?interval=today","duration":28288936,"bytes":33846,"addr":"172.17.0.1:34532","user":"WizardlyBump17"}
{"time":"2024-10-14T21:27:30.911075138Z","level":"INFO","msg":"[request]","status":200,"method":"GET","uri":"/settings","duration":5131457,"bytes":51201,"addr":"172.17.0.1:34532","user":"WizardlyBump17"}
{"time":"2024-10-14T21:27:35.871401247Z","level":"INFO","msg":"generating leaderboard after settings update","userID":"WizardlyBump17"}
{"time":"2024-10-14T21:27:35.871438497Z","level":"INFO","msg":"generating leaderboard","interval":"7_days","userCount":1,"aggregationCount":1}
{"time":"2024-10-14T21:27:35.872168405Z","level":"ERROR","msg":"failed to delete leaderboard items for user","userID":"WizardlyBump17","interval":"7_days","error":"attempt to write a readonly database (8)"}
{"time":"2024-10-14T21:27:35.872630772Z","level":"INFO","msg":"finished leaderboard generation"}
{"time":"2024-10-14T21:27:35.874038941Z","level":"INFO","msg":"[request]","status":500,"method":"POST","uri":"/settings","duration":3538481,"bytes":51398,"addr":"172.17.0.1:34532","user":"WizardlyBump17"}
```
<br>

I also am not able to integrate to WakaTime. I put my api key and I get: "Error: 500 internal server error". This the only line shown on the logs: 
```
{"time":"2024-10-14T21:31:43.937964428Z","level":"INFO","msg":"[request]","status":500,"method":"POST","uri":"/settings","duration":977812942,"bytes":51672,"addr":"172.17.0.1:43512","user":"WizardlyBump17"}
```
I have tried to manually specify the WakaTime api url and toggle the "Use legacy importer" option, but none of that works.
<br>

I believe those errors are related because they are both return the same 500 status.
<br>

**System information**
* Wakapi version: 2.12.1
* Operating system: Zorin OS 17.2, kernel: 6.8.0-45-generic
* Docker command:
```
docker run --init -it \
  -p 3000:3000 \
  -e "WAKAPI_PASSWORD_SALT=$SALT" \
  -v wakapi-data:/data \
  ghcr.io/muety/wakapi:latest
```
* Database: SQLite

**Comment by muety** [comment] 2024-10-14 22:21
Possible duplicate of #471, #477.

@YC I still didn't really get what's the problem there. Using the exact same docker run command, things work perfectly fine for me, even without manually adapting the database file permissions :thinking:.

**Closed by muety** 2024-10-14 22:21 UTC

**Comment by WizardlyBump17** [comment] 2024-10-14 22:35
> Possible duplicate of #471, #477.
> 
> @YC I still didn't really get what's the problem there. Using the exact same docker run command, things work perfectly fine for me, even without manually adapting the database file permissions 🤔. Can you explain, please?

i forgot to mention and idk if that is important, but I am not using docker as sudo. Maybe it has somrthing to do with that

**Comment by YC** [comment] 2024-10-15 10:52
This is slightly different to the linked issues, since it's Docker volume instead of bind mount.

These are the permissions if I inspect a **newly created volume** initialized from the provided command:
```
$ docker run --init -it -p 3000:3000 --entrypoint='' --user root -v wakapi-data:/data ghcr.io/muety/wakapi:latest bash
$ ls -la /data
total 152
drwxr-xr-x    1 app      app             18 Oct 15 10:40 .
drwxr-xr-x    1 root     root             8 Oct 15 10:42 ..
-rw-r--r--    1 app      app         151552 Oct 15 10:40 wakapi.db
```
Here, the `app` user can read and write the `wakapi.db`. 

@WizardlyBump17 Can you please try this, and post the output?

If you find that `wakapi.db` is owned by `root`, perhaps you can `chown app:app /data/wakapi.db`.
