### ISSUE TITLE
Add projects filter to `all_time_since_today` Wakatime compatible endpoint

### ISSUE THREAD

**Issue by devgianlu** [muety/wakapi#198] opened 2021-05-01 17:07 UTC
The title is self explanatory I think. I have tried looking at #58 if it was already listed, but the links don't show anything for me.

**Comment by muety** [comment] 2021-05-01 18:23
I see that filtering capability for the Wakatime endpoints is quite crucial. However, it is not that easy to realize due to the way summaries are currently computed. Implementing filtering would require #108 first.

I'll close this ticket as a duplicate of #58, but your request won't be forgotten!

**Closed** 2021-05-01 18:23 UTC
