### ISSUE TITLE
Wakatime "failed to fetch today" error in vscode

### ISSUE THREAD

**Issue by hashvIx3n** [muety/wakapi#243] opened 2021-09-03 14:19 UTC
WakaTime fails to sync data in vscode with wakapi. In the logs it says `"failed to make request to \"https://api.wakatime.com/api/v1/users/current/statusbar/today\"`
 
```
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:194","func":"runCmd","level":"error","message":"failed to run command: failed to fetch today: failed fetching today from api: failed to make request to \"https://api.wakatime.com/api/v1/users/current/statusbar/today\": Get \"https://api.wakatime.com/api/v1/users/current/statusbar/today\": unexpected EOF","now":"2021-09-03T13:35:35Z","version":"v1.22.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:194","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: won't send heartbeat due to backoff","now":"2021-09-03T13:35:37Z","version":"v1.22.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:194","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: won't send heartbeat due to backoff","now":"2021-09-03T13:40:40Z","version":"v1.22.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:194","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: won't send heartbeat due to backoff","now":"2021-09-03T13:40:50Z","version":"v1.22.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:194","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: won't send heartbeat due to backoff","now":"2021-09-03T13:40:52Z","version":"v1.22.1"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:194","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: won't send heartbeat due to backoff","now":"2021-09-03T13:40:54Z","version":"v1.22.1"}
```

Wakapi version: v1.22.1
Operating system: Windows 10

**Comment by muety** [comment] 2021-09-03 23:26
This issue is a duplicate of #153.

**Closed by muety** 2021-09-03 23:26 UTC
