### ISSUE TITLE
Error in disabled IPv6 system

### ISSUE THREAD

**Issue by samarulmeu** [muety/wakapi#661] opened 2024-07-25 08:04 UTC
I am running wakapi on Devuan 5 (Debian 12) and I have trouble when trying to run wakapi with IPv6 disabled in the system. 

This is the error I get

```
2024-07-25T10:59:03.700948862+03:00 [INFO ] 👉 Listening for HTTP on 127.0.0.1:3000... ✅
2024-07-25T10:59:03.701442753+03:00 [INFO ] 👉 Listening for HTTP on [::1]:3000... ✅
2024-07-25T10:59:03.701970314+03:00 [ERROR] listen tcp [::1]:3000: bind: cannot assign requested address
panic: listen tcp [::1]:3000: bind: cannot assign requested address

goroutine 54 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0x2593400?, {0xc000e60a00?, 0xc000e60a00?}, {0x0?, 0x0?, 0x0?})
        /home/runner/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:57 +0x37
github.com/emvi/logbuch.(*Logger).Fatal(0x2593400, {0xc000e60a00, 0x3c}, {0x0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0x72
github.com/emvi/logbuch.Fatal(...)
        /home/runner/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
main.listen.func5()
        /home/runner/work/wakapi/wakapi/main.go:426 +0x47
created by main.listen in goroutine 1
        /home/runner/work/wakapi/wakapi/main.go:424 +0x866
```

The line `listen_ipv6: #::1` has no effect in disabling the server.  The only workaround is to enable again IPv6.

Thank for your help. 

P. S. In the config file there is the comment `# set to '-' to disable ipv6` but writing something like `listen_ipv6: -` triggers an error. Maybe the comment is misleading?

**Comment by muety** [comment] 2024-07-25 08:41
Duplicate of #620, #584.

In YAML, set `listen_ipv6: ''`, as explained in the docs.

**Closed by muety** 2024-07-25 08:41 UTC

**Comment by samarulmeu** [comment] 2024-07-25 08:50
Thank you! It is working. The fact is that the documentation is misleading it says `set to '-' to disable ipv6` not `set to ''` as I mentioned above.
