### ISSUE TITLE
Importing Wakatime JSON exports

### ISSUE THREAD

**Issue by PotatoPlank** [muety/wakapi#72] opened 2020-11-10 02:22 UTC
Is there currently a plan to allow for importing JSON exports provided by Wakatime? This would be a beneficial feature for those looking to switch from Wakatime to a self-hosted solution.

**Comment by muety** [comment] 2020-11-10 07:42
Hi @PotatoPlank, thanks for your feature request. Having the ability to import data from Wakatime would indeed be a desirable functionality.

However, a major issue here is the fact that you can only export aggregated data, i.e. summaries, from Wakatime. As far as I know, there is no way to download raw heartbeats, as they're potentially not even persisted on their side anyway.

In Wakapi, heartbeats are the "source of truth", while aggregated summaries are considered volatile and are being derived from heartbeats. Wakapi bases on the assumption that summaries can be dropped and recomputed at any time. We would lose this flexibility if we imported prepared summaries from Wakatime.

What we could to is distinguish between volatile and persistent summaries, whereas such imported from Wakatime would have a flag like `persistent: true`, indicating that they must not be deleted ever. This would certainly add complexity to out summary computation logic, but enables for a valuable feature on the other hand.

Somebody else interested in this as well?

**Comment by PotatoPlank** [comment] 2020-11-10 14:52
Hi @muety, makes sense. You're correct that all of the data they provide is just summaries. 

I took a brief look at the Wakapi database structure to get an idea how the summaries were being calculated. I personally didn't see how the Wakatime data could be easily imported.

The persistent flag sounds like a good idea. If I think of anything else, I'll add it here.

Thanks for the response!

**Comment by muety** [comment] 2021-01-12 20:14
Duplicate of #87.

**Closed by muety** 2021-01-12 20:14 UTC
Labels: enhancement
