### ISSUE TITLE
SSO integration (OIDC)

### ISSUE THREAD

**Issue by DenuxPlays** [muety/wakapi#626] opened 2024-03-21 07:09 UTC
Hey,

I found [this issue](https://github.com/muety/wakapi/issues/295) and wondered if it's possible to implement a general SSO feature. I've already connected almost all of my self-hosted services (Nextcloud, Immich, and hopefully soon Vaultwarden and more) with Authentik, and I would like to do the same with Wakapi.

I opened a separate issue because I simply hate LDAP and I love OIDC.

I would love to implement this feature, but I don't have any experience in Go, and more importantly, I don't have time at the moment. So maybe someone else can implement this.

**Comment by muety** [comment] 2024-03-21 07:15
Hi @DenuxPlays, thanks for requesting this. I definitely see how OIDC support would be a huge benefit. There is an open ticket for this already, but I'll revisit it's prioritization. 

Duplicate of #33.

**Closed by muety** 2024-03-21 07:15 UTC

**Comment by DenuxPlays** [comment] 2024-03-21 07:25
> Hi @DenuxPlays, thanks for requesting this. I definitely see how OIDC support would be a huge benefit. There is an open ticket for this already, but I'll revisit it's prioritization.
> 
> Duplicate of #33.

Ah okay. Thank you :)
